# Numpy refreshing

In [8]:
import numpy as np

a = np.array([100, 22, 33, 48, 28])
print(type(a))
print(a.shape)
print(a[0], a[3], a[2], a[4], a[1])
a[3] = 5
print(a)

b = np.array([[1,2,3,4],[4,5,6,4]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 3])

<class 'numpy.ndarray'>
(5,)
100 48 33 28 22
[100  22  33   5  28]
(2, 4)
1 2 4


In [15]:
a = np.zeros((3,3))

b = np.ones((2,2))

c = np.full((2,3), 54)

d = np.eye(2)

e = np.random.random((2,5))

abcde = [a,b,c,d,e]

for i in abcde:
    print(i)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[54 54 54]
 [54 54 54]]
[[1. 0.]
 [0. 1.]]
[[0.40472369 0.17445987 0.94186621 0.33301964 0.77405726]
 [0.21143874 0.48827561 0.73462701 0.47583522 0.95083533]]


In [21]:
a = np.array([[1,4,3,8],[43,31,82,92],[32,82,98,89]])
print(a[1:,2:])

print(a[1,3])
a[1,3] = 555
print(a[1,3])

[[82 92]
 [98 89]]
92
555


In [26]:
a = np.array([[1,4,3,8],[43,31,82,92],[32,82,98,89]])

row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

print('\n')

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[43 31 82 92] (4,)
[[43 31 82 92]] (1, 4)


[ 4 31 82] (3,)
[[ 4]
 [31]
 [82]] (3, 1)


In [29]:
print(a[[1,2,1,0],[0,3,2,3]])
print(np.array([a[1,0],a[2,3],a[1,2],a[0,3]]))

[43 89 82  8]
[43 89 82  8]


In [35]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0,0,2,2])
print(a[np.arange(4),b])

a[np.arange(4), b] *= 10
print(a)

[ 1  4  9 12]
[[ 10   2   3]
 [ 40   5   6]
 [  7   8  90]
 [ 10  11 120]]


In [38]:
x = np.array([1, 2])
print(x.dtype)

y = np.array([1.0, 2.2])
print(y.dtype)

z = np.array([1, 2], dtype = np.int64)
print(z.dtype)

int32
float64
int64


In [42]:
x = np.array([[2,2,3],[3,5,9]])
y = np.array([[8,7,3],[3,3,1]])

print(x+y)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.divide(x,y))
print(np.multiply(x,y))
print(np.sqrt(x))

[[10  9  6]
 [ 6  8 10]]
[[10  9  6]
 [ 6  8 10]]
[[-6 -5  0]
 [ 0  2  8]]
[[0.25       0.28571429 1.        ]
 [1.         1.66666667 9.        ]]
[[16 14  9]
 [ 9 15  9]]
[[1.41421356 1.41421356 1.73205081]
 [1.73205081 2.23606798 3.        ]]


In [43]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

219
219


In [45]:
y = np.array([[5,6],[7,8]])

print(np.sum(y))
print(np.sum(y, axis = 0))
print(np.sum(y, axis = 1))

x = y.T
print(x)

26
[12 14]
[11 15]
[[5 7]
 [6 8]]


In [46]:
r = np.array([[1,4,6],[8,4,9],[9,3,1],[10,11,28]])
x = np.array([10,10,10])
u = np.empty_like(r)

for i in range(4):
    u[i,:] = r[i,:] + x
    
print(u)

[[11 14 16]
 [18 14 19]
 [19 13 11]
 [20 21 38]]
